// <auto-generated />
using System;
using BackgroundService.EntityFrameworkCore.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackgroundService.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(BackgroundServiceDbContext))]
    partial class BackgroundServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackgroundService.EntityFrameworkCore.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatePwd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e0c4f2a-83c9-4df6-990f-e4042b1b1ff5"),
                            Email = "test1@gmail.com",
                            LastUpdatePwd = new DateTime(2024, 1, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1848),
                            Status = "Default"
                        },
                        new
                        {
                            Id = new Guid("8b034e98-f3d4-4e72-8c96-c4af64a1e6d1"),
                            Email = "test2@gmail.com",
                            LastUpdatePwd = new DateTime(2023, 12, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1871),
                            Status = "Default"
                        },
                        new
                        {
                            Id = new Guid("bf30d40c-889f-4061-b903-de738d872f0b"),
                            Email = "test3@gmail.com",
                            LastUpdatePwd = new DateTime(2023, 11, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1874),
                            Status = "Default"
                        },
                        new
                        {
                            Id = new Guid("5ad5c06a-1e4f-4e4c-b9b8-e7eaa7183ce2"),
                            Email = "test4@gmail.com",
                            LastUpdatePwd = new DateTime(2023, 10, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1876),
                            Status = "Default"
                        },
                        new
                        {
                            Id = new Guid("91ac6ccb-f63f-4f37-b8b6-7ccdf344d2d6"),
                            Email = "test5@gmail.com",
                            LastUpdatePwd = new DateTime(2023, 9, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1887),
                            Status = "Default"
                        },
                        new
                        {
                            Id = new Guid("963810c9-f315-4c7f-bca5-41767b18d0d6"),
                            Email = "test6@gmail.com",
                            LastUpdatePwd = new DateTime(2023, 8, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1890),
                            Status = "Default"
                        },
                        new
                        {
                            Id = new Guid("54514b74-4697-42d0-b721-6d1746503991"),
                            Email = "test7@gmail.com",
                            LastUpdatePwd = new DateTime(2023, 7, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1892),
                            Status = "Default"
                        },
                        new
                        {
                            Id = new Guid("37685deb-c7ca-4190-8736-37cc8f50e703"),
                            Email = "test8@gmail.com",
                            LastUpdatePwd = new DateTime(2023, 6, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1894),
                            Status = "Default"
                        },
                        new
                        {
                            Id = new Guid("e6778ee3-41f9-496f-9f80-3134c5cdb95b"),
                            Email = "test9@gmail.com",
                            LastUpdatePwd = new DateTime(2023, 5, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1896),
                            Status = "Default"
                        },
                        new
                        {
                            Id = new Guid("a363f9d1-210f-42c1-adfc-e21f95d633de"),
                            Email = "test10@gmail.com",
                            LastUpdatePwd = new DateTime(2023, 4, 24, 14, 52, 45, 519, DateTimeKind.Local).AddTicks(1898),
                            Status = "Default"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
